function set_femm_problem_definition(MD)
%%Set FEMM problem definition

mi_probdef( MD.ModelFrequency, ...
  MD.ModelUnit, ...
  MD.ModelType, ...
  MD.ModelPrecision, ...
  MD.StackLength*MD.PackFactor, ...
  MD.MeshMinAngle, ...
  MD.ACSolver);

end % function