%% This script sets the most common plot properties 
% The objects handle 'h' should exist to set the relative properties

%% Label properties
if isfield(h, 'LabelX')
  set(h.LabelX, ...
    'Fontname', PlotProp.FontName.Label, ...
    'FontSize', PlotProp.FontSize.Label, ...
    'Fontweight', PlotProp.FontWeight.Label);
end

if isfield(h, 'LabelY')
  set(h.LabelY, ...
    'Fontname', PlotProp.FontName.Label, ...
    'FontSize', PlotProp.FontSize.Label, ...
    'Fontweight', PlotProp.FontWeight.Label);
end

%% Legend properties
if isfield(h, 'Legend')
  set(h.Legend, ...
    'Fontname', PlotProp.FontName.Legend, ...
    'FontSize', PlotProp.FontSize.Legend, ...
    'Fontweight', PlotProp.FontWeight.Legend);
end

%% Axes properties
set(gca, 'FontSize', PlotProp.FontSize.Axis, 'Fontname', PlotProp.FontName.Axis, 'FontWeight', PlotProp.FontWeight.Axis)
